### ISSUE TITLE
this is built in functionality already.

### ISSUE THREAD

**Issue by dwaindibbly** [r-blau/youtube-parser#1]
this does the same thing.

```dart
String getIdFromUrl(String url) {
  Uri someLink = Uri.parse(url); // get the uri of the link (look at the normal new Uri() constructor for what it can do)
  if (someLink.host == 'www.youtube.com') { // are we at youtube?
    return someLink.queryParameters['v']; //return the video id (do checks on it too maybe?)
  }
}
```

**Comment by r-blau** [comment]
Your function works for default youtube links with "?v=..." at the end, but they come in multiple fashions. It would fail on a link like "https://youtu.be/xxxxxxxx" for example.

The purpose of this library is to make it work on every style of YouTube link.

**Comment by dwaindibbly** [comment]
Add this then:

```dart
if (someLink.host == 'youtu.be') {
  return (someLink.pathSegments.length >= 2) ? someLink.pathSegments[1] : '';
}
```

**Comment by r-blau** [comment]
Although I like the clearness of your solution, it does **not** do the same as the current implementation.
Your functions both allow invalid video IDs, whereas mine do not.

I guess one could argue that the function _should_ accept invalid video IDs, but that's another topic.
